### ISSUE TITLE
 background color not evenly applied

### ISSUE THREAD

**Issue by o-** [terminalpp/tpp#2]
on X11 the background color seems to be only applied to area with characters.

see this example, where I set the bg to red:

![Screenshot_2019-12-09_17-14-32](https://user-images.githubusercontent.com/710933/70452498-7dc2cb00-1aa7-11ea-9b68-2a38b691ffd3.png)

**Comment by zduka** [comment]
I believe this is not a bug, checked xterm, whose terminfo tpp uses and it behaves the same.
